//! Shared IWA archive encoding primitives used by all three app writers.

use crate::iwa::{IwaArchive, IwaArchiveDescriptor, IwaObjectReference, IwaPacket};
use crate::protobuf::{ProtoField, ProtoMessage};
use crate::Error;

/// `MessageInfo.version` triple carried by every real archive header.
pub(crate) const ARCHIVE_VERSION: [u8; 3] = [1, 0, 5];

/// Synthesizes an `IwaPacket` header for a freshly encoded body with no
/// cross-archive object references.
pub(crate) fn synthesize_header(
    root_object_id: u64,
    kind: u64,
    body_len: usize,
) -> Result<IwaPacket, Error> {
    synthesize_header_with_references(root_object_id, kind, body_len, Vec::new())
}

/// Synthesizes an `IwaPacket` header for a freshly encoded body, recording
/// `object_references` so the IWA reader can resolve cross-archive links.
pub(crate) fn synthesize_header_with_references(
    root_object_id: u64,
    kind: u64,
    body_len: usize,
    object_references: Vec<IwaObjectReference>,
) -> Result<IwaPacket, Error> {
    let descriptor = IwaArchiveDescriptor {
        root_object_id: Some(root_object_id),
        kind_hint: Some(kind),
        message_version: Some(ARCHIVE_VERSION.to_vec()),
        body_hint: Some(
            u64::try_from(body_len).map_err(|_| Error::InvalidIwa("body length overflow"))?,
        ),
        object_references,
    };
    Ok(IwaPacket::new(descriptor.encode_message()?.encode()?))
}

/// Encodes a minimal archive that contains only an empty body object of the
/// given type, rooted at `root_object_id`.
pub(crate) fn encode_empty_archive(root_object_id: u64, kind: u64) -> Result<Vec<u8>, Error> {
    let header = synthesize_header(root_object_id, kind, 0)?;
    IwaArchive::encode(header, Vec::new())
}

/// Encodes a protobuf object-reference message: `{ field 1: object_id }`.
///
/// This is the wire format used for cross-object references in iWork archives
/// (both within and across `.iwa` files).
pub(crate) fn object_reference(object_id: u64) -> Result<Vec<u8>, Error> {
    ProtoMessage::new(vec![ProtoField::varint(1, object_id)]).encode()
}

/// Produces the `Metadata/Properties.plist` content shared by all iWork apps.
///
/// The file format version and UUIDs use placeholder strings that identify
/// packages generated by this crate.
pub(crate) fn properties_plist() -> Vec<u8> {
    br#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>documentUUID</key>
  <string>iwork-rs-generated-document</string>
  <key>fileFormatVersion</key>
  <string>14.4.1</string>
  <key>isMultiPage</key>
  <false/>
  <key>revision</key>
  <string>1</string>
  <key>stableDocumentUUID</key>
  <string>iwork-rs-generated-document</string>
  <key>versionUUID</key>
  <string>iwork-rs-generated-version</string>
</dict>
</plist>
"#
    .to_vec()
}

/// Content for `Metadata/DocumentIdentifier`.
pub(crate) fn document_identifier() -> Vec<u8> {
    b"iwork-rs-generated-document".to_vec()
}

/// Content for `Metadata/BuildVersionHistory.plist`.
pub(crate) fn build_version_history_plist() -> Vec<u8> {
    br#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
  <dict>
    <key>app</key>
    <string>iwork-rs</string>
    <key>version</key>
    <string>0.1.0</string>
  </dict>
</array>
</plist>
"#
    .to_vec()
}

/// Encodes the standard cross-app infrastructure archives common to all iWork
/// packages: `DocumentMetadata`, `Metadata`, `ObjectContainer`,
/// `AnnotationAuthorStorage`, and `DocumentStylesheet`.
///
/// Callers must supply the `document_root_id` that the metadata archives
/// reference back to, and the stylesheet root ID.
pub(crate) struct InfraArchives {
    pub document_metadata: Vec<u8>,
    pub metadata: Vec<u8>,
    pub object_container: Vec<u8>,
    pub annotation_author_storage: Vec<u8>,
    pub document_stylesheet: Vec<u8>,
}

pub(crate) fn encode_infra_archives(
    document_root_id: u64,
    metadata_root_id: u64,
    object_container_root_id: u64,
    document_metadata_root_id: u64,
    annotation_root_id: u64,
    stylesheet_root_id: u64,
) -> Result<InfraArchives, Error> {
    let document_metadata = {
        let body = ProtoMessage::new(vec![
            ProtoField::varint(1, 0),
            ProtoField::bytes(3, Vec::new()),
        ])
        .encode()?;
        let header = synthesize_header_with_references(
            document_metadata_root_id,
            11011,
            body.len(),
            vec![IwaObjectReference {
                object_id: Some(document_root_id),
                kind_hint: Some(3),
                state_hint: Some(1),
            }],
        )?;
        IwaArchive::encode(header, body)?
    };

    let metadata = {
        let body = ProtoMessage::new(vec![
            ProtoField::varint(1, 0),
            ProtoField::bytes(2, object_reference(document_root_id)?),
            ProtoField::bytes(3, object_reference(document_metadata_root_id)?),
            ProtoField::bytes(4, object_reference(object_container_root_id)?),
        ])
        .encode()?;
        let header = synthesize_header_with_references(
            metadata_root_id,
            11006,
            body.len(),
            vec![IwaObjectReference {
                object_id: Some(document_root_id),
                kind_hint: Some(1),
                state_hint: Some(1),
            }],
        )?;
        IwaArchive::encode(header, body)?
    };

    let object_container = {
        let body = ProtoMessage::new(vec![
            ProtoField::varint(1, 0),
            ProtoField::bytes(2, object_reference(document_root_id)?),
        ])
        .encode()?;
        let header = synthesize_header(object_container_root_id, 11008, body.len())?;
        IwaArchive::encode(header, body)?
    };

    let annotation_author_storage = encode_empty_archive(annotation_root_id, 11009)?;

    let document_stylesheet = {
        let body = ProtoMessage::new(vec![
            ProtoField::message(
                2,
                &ProtoMessage::new(vec![
                    ProtoField::string(1, "Normal"),
                    ProtoField::bytes(2, object_reference(stylesheet_root_id)?),
                ]),
            )?,
            ProtoField::message(
                2,
                &ProtoMessage::new(vec![
                    ProtoField::string(1, "Bold"),
                    ProtoField::bytes(2, object_reference(stylesheet_root_id + 1)?),
                    ProtoField::message(11, &ProtoMessage::new(vec![ProtoField::varint(1, 1)]))?,
                ]),
            )?,
        ])
        .encode()?;
        let header = synthesize_header_with_references(
            stylesheet_root_id,
            2,
            body.len(),
            vec![IwaObjectReference {
                object_id: Some(document_root_id),
                kind_hint: Some(1),
                state_hint: Some(0),
            }],
        )?;
        IwaArchive::encode(header, body)?
    };

    Ok(InfraArchives {
        document_metadata,
        metadata,
        object_container,
        annotation_author_storage,
        document_stylesheet,
    })
}
